#!/usr/bin/env python
# coding: utf-8
import sys
import logging
from docopt import docopt
from bear import Bear
from bear import __version__

doc = """Bear, RSS feed in your Inbox.

Usage:
    bear init-config [--settings=<path>]
    bear add <url> [--settings=<path>] [options]
    bear delete <id> [--settings=<path>] [options]
    bear reset <id> [--settings=<path>] [options]
    bear feeds [--settings=<path>] [options]
    bear fetch <id> [--settings=<path>] [options]
    bear fetch-all [--settings=<path>] [options]
    bear help-plugin <name>

Options:
    --settings=<path>     Settings file path [default: bear.ini]
    --no-email            Don't send email
    --log-level=<level>   Log level
"""

if __name__ == '__main__':
    args = docopt(doc, version=__version__)

    bear = Bear(settings_path=args.get('--settings'), cli_opts=args)
    bear.initialize_db()

    try:
        if args.get('<id>'):
            _id = int(args.get('<id>'))
    except ValueError:
        logging.error('<id> must be an integer.')
        sys.exit(1)

    if args.get('feeds'):
        feeds = bear.get_feeds()
        for feed in feeds:
            logging.info('[%s] %s (added:%s) (updated:%s)' % (
                feed.id, feed.url, feed.added, feed.updated))
    elif args.get('delete'):
        bear.delete_feed(feed_id=args.get('<id>'))
    elif args.get('add'):
        bear.add_feed(args.get('<url>'))
    elif args.get('fetch'):
        bear.fetch_feed(feed_id=args.get('<id>'))
    elif args.get('fetch-all'):
        feeds = bear.get_feeds()
        logging.info('[info] %s feeds found.' % feeds.count())
        for feed in feeds:
            bear.fetch_feed(feed_id=feed.id)
    elif args.get('init-db'):
        bear.initialize_db()
    elif args.get('init-config'):
        bear.initialize_config()
    elif args.get('reset'):
        bear.reset_feed(feed_id=args.get('<id>'))
    elif args.get('help-plugin'):
        d = bear.plugin_manager.get_plugin_help(args.get('<name>'))
        if d:
            print(d)
    logging.info('[info] Done.')
